import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the prompt canvas shell", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>Agent Canvas · 多 Skill 视觉工作流画板<\/title>/i);
  assert.match(html, /正在载入节点画板/);
  assert.doesNotMatch(html, /Your site is taking shape|codex-preview|react-loading-skeleton/i);

  const flowSource = await readFile(new URL("../app/FlowCanvas.tsx", import.meta.url), "utf8");
  assert.match(flowSource, /Agent Canvas/);
  assert.match(flowSource, /API_KEY_FIELDS/);
  assert.match(flowSource, /className="api-key-settings-button"/);
  assert.match(flowSource, /\/api-key-settings/);
  assert.match(flowSource, /保存并刷新渠道/);
  assert.match(flowSource, /真实值不会回显/);
  assert.match(flowSource, /type ThemePreference = "light" \| "dark" \| "system"/);
  assert.match(flowSource, /THEME_STORAGE_KEY = "agent-canvas-theme"/);
  assert.match(flowSource, /aria-label="界面主题"/);
  assert.match(flowSource, /<option value="system">跟随系统<\/option>/);
  assert.match(flowSource, /window\.localStorage\.setItem\(THEME_STORAGE_KEY, themePreference\)/);
  assert.match(flowSource, /media\.addEventListener\("change", syncTheme\)/);
  assert.match(flowSource, /delete data\.generatedImages/);
  assert.match(flowSource, /delete data\.generatedVideos/);
  assert.match(flowSource, /QuotaExceededError/);
  assert.match(flowSource, /图片与视频保存目录/);
  assert.match(flowSource, /\/media-settings/);
  assert.match(flowSource, /上传 \/ 替换图片/);
  assert.match(flowSource, /上传 \/ 替换视频/);
  assert.match(flowSource, /function VideoNode/);
  assert.match(flowSource, /NodeResizer/);
  assert.match(flowSource, /function ReferenceNode\(\{ data, selected \}/);
  assert.match(flowSource, /<NodeResizer[\s\S]*?isVisible=\{selected\}[\s\S]*?minWidth=\{280\}[\s\S]*?minHeight=\{320\}/);
  assert.match(flowSource, /function copyableNode/);
  assert.match(flowSource, /function duplicatedNode/);
  assert.match(flowSource, /delete data\.threadId/);
  assert.match(flowSource, /不包含连线/);
  assert.match(flowSource, /clipboard\.edges \|\| \[\]/);
  assert.match(flowSource, /const copiedEdges = clipboardSelectionEdges\(edges, copiedNodes\)/);
  assert.match(flowSource, /function clipboardSelectionEdges/);
  assert.match(flowSource, /function pasteClipboardEdges/);
  assert.match(flowSource, /copiedIds\.has\(edge\.source\) && copiedIds\.has\(edge\.target\)/);
  assert.match(flowSource, /previewEdgeIds/);
  assert.match(flowSource, /altDragCopyStateRef/);
  assert.match(flowSource, /finishAltDragCopy/);
  assert.match(flowSource, /原节点和连线保持原位/);
  assert.match(flowSource, /modifier && key === "c"/);
  assert.match(flowSource, /modifier && key === "v"/);
  assert.match(flowSource, /event\.key !== "Delete" && event\.key !== "Backspace"/);
  assert.match(flowSource, /const undoCanvas = useCallback/);
  assert.match(flowSource, /const redoCanvas = useCallback/);
  assert.match(flowSource, /modifier && key === "z"/);
  assert.match(flowSource, /modifier && key === "y"/);
  assert.match(flowSource, /function CanvasGroupNode/);
  assert.match(flowSource, /aria-label="重命名群组"/);
  assert.match(flowSource, /aria-label="群组名称"/);
  assert.match(flowSource, /nextTitle !== title.*data\.onUpdate/);
  assert.match(flowSource, /handleClassName="group-resize-handle"/);
  assert.match(flowSource, /lineClassName="group-resize-line"/);
  assert.match(flowSource, /const groupSelectedNodes = useCallback/);
  assert.match(flowSource, /const ungroupSelectedNodes = useCallback/);
  assert.match(flowSource, /modifier && key === "g"/);
  assert.match(flowSource, /modifier && event\.key === "Backspace"/);
  assert.match(flowSource, /parentId: groupId/);
  assert.match(flowSource, /extent: "parent" as const/);
  assert.match(flowSource, /expandParent: true/);
  assert.match(flowSource, /clipboardSelectionNodes/);
  assert.match(flowSource, /pasteClipboardNodes/);
  assert.match(flowSource, /"group",[\s\S]*?"reference"/);
  assert.match(flowSource, /MAX_HISTORY_ENTRIES = 50/);
  assert.doesNotMatch(flowSource, />复制结果<\/button>/);
  assert.match(flowSource, /function blockMiddleMouseDownload/);
  assert.match(flowSource, /onMouseDown=\{blockMiddleMouseDownload\} onAuxClick=\{blockMiddleMouseDownload\}/);
  assert.match(flowSource, /const onNodeDragStart = useCallback/);
  assert.match(flowSource, /multiSelectionKeyCode="Shift"/);
  assert.match(flowSource, /className="canvas-shortcuts-hint"/);
  assert.match(flowSource, /const REWRITE_NODE_TITLE = "编辑改写"/);
  assert.match(flowSource, /type PromptSkillId = "seedance" \| "image" \| "photoreal"/);
  assert.match(flowSource, /Seedance 视频提示词/);
  assert.match(flowSource, /Image 图像提示词/);
  assert.match(flowSource, /真实感场景与模特图/);
  assert.match(flowSource, /提示词 Skill/);
  assert.match(flowSource, /isImagePromptSkill/);
  assert.match(flowSource, /const ASPECT_RATIOS = \["Auto", "1:1", "9:16", "16:9", "3:4", "4:3", "3:2", "2:3", "5:4", "4:5", "21:9"\]/);
  assert.match(flowSource, /function ImageGeneratorNode/);
  assert.match(flowSource, /imagegenerator: ImageGeneratorNode/);
  assert.match(flowSource, /function VideoGeneratorNode/);
  assert.match(flowSource, /videogenerator: VideoGeneratorNode/);
  assert.match(flowSource, /function TextBoxNode/);
  assert.match(flowSource, /text: TextBoxNode/);
  assert.match(flowSource, /请先把图片生成节点连接到一个图片节点/);
  assert.match(flowSource, /请先把视频生成节点连接到一个视频节点/);
  assert.match(flowSource, /source\.type === "imagegenerator" && isImageOutputNodeType\(target\.type\)/);
  assert.match(flowSource, /source\.type === "videogenerator" && isVideoOutputNodeType\(target\.type\)/);
  assert.match(flowSource, /上传、预览或接收生成图片/);
  assert.match(flowSource, /上传、播放或接收生成视频/);
  const imageNodeSource = flowSource.slice(flowSource.indexOf("function ImageGeneratorNode"), flowSource.indexOf("function VideoGeneratorNode"));
  assert.doesNotMatch(imageNodeSource, /生图 Skill|skill-selector/);
  assert.match(flowSource, /MAX_IMAGE_GENERATION_IMAGES = 12/);
  assert.match(flowSource, /IMAGE_GENERATION_RESOLUTIONS.*\["1K", "2K", "4K"\]/);
  assert.match(flowSource, /type ImageGenerationProvider = "openrouter" \| "google" \| "comfly"/);
  assert.match(flowSource, /IMAGE_GENERATION_PROVIDER_IDS.*\["openrouter", "google", "comfly"\]/);
  assert.match(flowSource, /图片模型供应商/);
  assert.match(flowSource, /Google 官方/);
  assert.match(flowSource, /暂无可用模型/);
  assert.match(flowSource, /参考输入 · 最多 12 张图片/);
  assert.match(flowSource, /id="prompt" className="prompt-handle"/);
  assert.match(flowSource, /readOnly=\{promptConnected\}/);
  assert.match(flowSource, /source\.type === "text"/);
  assert.match(flowSource, /target\.type === "imagegenerator"/);
  assert.match(flowSource, /delete data\.promptConnected/);
  assert.match(flowSource, /delete data\.promptInput/);
  assert.match(flowSource, /delete data\.imageProviderOptions/);
  assert.match(flowSource, /const runImageGeneration = useCallback/);
  assert.match(flowSource, /kind: "image-generation"/);
  assert.match(flowSource, /kind: "video-generation"/);
  assert.match(flowSource, /@视频/);
  assert.match(flowSource, /全能参考/);
  const imageControlsSource = flowSource.slice(flowSource.indexOf("function ImageGenerationModelControls"), flowSource.indexOf("function ImageGeneratorNode"));
  assert.doesNotMatch(imageControlsSource, /思考强度|reasoningEffort/);
  assert.match(flowSource, /参考输入 · 图片最多 9 张 \/ 视频最多 3 个/);
  assert.match(flowSource, /@视频/);
  assert.match(flowSource, /targetHandle: "media-1"/);
  assert.doesNotMatch(flowSource, /text-input-port/);
  assert.doesNotMatch(flowSource, /deletable: false/);
  assert.match(flowSource, /画布文件/);
  assert.match(flowSource, /自动命名当前画布/);
  assert.match(flowSource, /saveCanvasProject/);
  assert.match(flowSource, /const OPEN_PROJECTS_KEY = "prompt-flow-open-projects"/);
  assert.match(flowSource, /className="canvas-tab-list" role="tablist" aria-label="已打开的画布"/);
  assert.match(flowSource, /className="canvas-tab-main" role="tab" aria-selected=\{active\}/);
  assert.match(flowSource, /aria-controls="canvas-workspace-panel"/);
  assert.match(flowSource, /const openProjects = useMemo/);
  assert.match(flowSource, /const closeCanvasTab = useCallback/);
  assert.match(flowSource, /至少需要保留一个画布标签/);
  assert.match(flowSource, /accept="\.promptflow\.json,\.json,application\/json"/);
  assert.match(flowSource, /打开画布文件/);
  assert.match(flowSource, /const saveCanvasAs = useCallback/);
  assert.match(flowSource, /已另存为.*原画布未被覆盖/);
  assert.match(flowSource, /const exportCanvas = useCallback/);
  assert.match(flowSource, /format: "prompt-flow-canvas"/);
  assert.match(flowSource, /version: 1/);
  assert.match(flowSource, /new Blob\(\[JSON\.stringify\(payload, null, 2\)\], \{ type: "application\/json" \}\)/);
  assert.match(flowSource, /URL\.createObjectURL\(blob\)/);
  assert.match(flowSource, /anchor\.download = `\$\{safeName \|\| "Agent Canvas 画布"\}\.promptflow\.json`/);
  assert.match(flowSource, /URL\.revokeObjectURL\(url\)/);
  assert.match(flowSource, /const importCanvasFile = useCallback/);
  assert.match(flowSource, /const imported = parsePortableCanvas\(raw\)/);
  assert.match(flowSource, /const importCanvasFile[\s\S]*?const id = crypto\.randomUUID\(\)[\s\S]*?saveCanvasProject\(id, name, sanitized\.nodes, sanitized\.edges\)/);
  assert.match(flowSource, /value\.format !== "prompt-flow-canvas" \|\| value\.version !== 1/);
  assert.match(flowSource, /project\.nodes\.length > MAX_PORTABLE_NODES/);
  assert.match(flowSource, /project\.edges\.length > MAX_PORTABLE_EDGES/);
  assert.match(flowSource, /!PORTABLE_NODE_TYPES\.has\(item\.type\)/);
  assert.match(flowSource, /nodeIds\.has\(item\.id\)/);
  assert.match(flowSource, /!Number\.isFinite\(item\.position\.x\) \|\| !Number\.isFinite\(item\.position\.y\)/);
  assert.match(flowSource, /edgeIds\.has\(item\.id\)/);
  assert.match(flowSource, /!nodeIds\.has\(item\.source\) \|\| !nodeIds\.has\(item\.target\)/);
  assert.match(flowSource, /画布文件不是有效的 JSON/);

  const projectNodesStart = flowSource.indexOf("function projectNodes");
  const portableNodesStart = flowSource.indexOf("function portableProjectNodes");
  const portableTypesStart = flowSource.indexOf("const PORTABLE_NODE_TYPES");
  assert.ok(projectNodesStart >= 0 && portableNodesStart > projectNodesStart && portableTypesStart > portableNodesStart);
  const projectNodesSource = flowSource.slice(projectNodesStart, portableNodesStart);
  const portableNodesSource = flowSource.slice(portableNodesStart, portableTypesStart);
  assert.doesNotMatch(projectNodesSource, /delete data\.(?:imageData|videoData|fileName)/);
  assert.match(portableNodesSource, /projectNodes\(nodes\)/);
  assert.match(portableNodesSource, /delete data\.threadId/);
  assert.match(flowSource, /structuredClone\(portableProjectNodes\(nodes\)\)/);
  assert.match(flowSource, /project: \{ name: projectName, nodes: portableProjectNodes\(nodes\), edges \}/);
  assert.match(flowSource, /completeCanvas\(portableProjectNodes\(imported\.nodes\), imported\.edges\)/);
  assert.match(flowSource, /type AgentProvider = "codex" \| "openrouter" \| "comfly" \| "grok-build"/);
  assert.match(flowSource, /const PROVIDERS: AgentProvider\[\] = \["codex", "openrouter", "comfly", "grok-build", "antigravity"\]/);
  assert.match(flowSource, /模型供应商/);
  assert.match(flowSource, /OpenRouter/);
  assert.match(flowSource, /comfly: "Comfly"/);
  assert.match(flowSource, /Comfly 处理中/);
  assert.match(flowSource, /Grok Build/);
  assert.match(flowSource, /antigravity: "Antigravity"/);
  assert.match(flowSource, /"antigravity"/);
  assert.match(flowSource, /Antigravity 处理中/);
  assert.match(flowSource, /extra_high: "超高"/);
  assert.match(flowSource, /auto: "自动"/);
  assert.match(flowSource, /思考强度/);
  assert.match(flowSource, /左右连线，支持复制与粘贴/);
  assert.match(flowSource, /const FLOW_PRESETS/);
  assert.match(flowSource, /常规提示词/);
  assert.match(flowSource, /拖入一段已连线流程/);
  assert.match(flowSource, /targetHandle: "media-1"/);
  assert.match(flowSource, /handleCanvasPresetDrop/);
  assert.match(flowSource, /application\/x-agent-canvas-preset/);
  assert.match(flowSource, /nodes\.length \+ 3 > MAX_PORTABLE_NODES/);
  assert.doesNotMatch(flowSource, /加入预设后会超过图片或视频节点上限/);
  assert.doesNotMatch(flowSource, /当前画布最多添加 12 张参考图/);
  assert.match(flowSource, />复制<\/button><button onClick=\{data\.onPaste\}>粘贴</);
  assert.match(flowSource, /taskMode: "revision"/);
  assert.match(flowSource, /节点库/);
  assert.match(flowSource, /<b>文本框<\/b>/);
  assert.match(flowSource, /function PromptEditorNode/);
  assert.match(flowSource, /编辑提示词/);
  assert.match(flowSource, /navigator\.clipboard\.readText/);
  assert.match(flowSource, /navigator\.clipboard\?\.read/);
  assert.match(flowSource, /粘贴剪贴板图片/);
  assert.match(flowSource, /window\.addEventListener\("paste", handleImagePaste\)/);
  assert.match(flowSource, /剪贴板图片超过 15MB/);
  assert.match(flowSource, /onDrop=\{handleImageFileDrop\}/);
  assert.match(flowSource, /Array\.from\(event\.dataTransfer\.files\)/);
  assert.match(flowSource, /className=\{imageDropActive \? "is-image-drop-active" : ""\}/);
  assert.match(flowSource, /const selectedNodes = nodes\.filter\(\(node\) => node\.selected\);\s*if \(selectedNodes\.length === 1 && selectedNodes\[0\]\.type === "reference"\) return;/s);
  assert.match(flowSource, /选中节点后按 Ctrl\+V 粘贴/);
  assert.match(flowSource, /className="image-preview-card"/);
  assert.match(flowSource, /className="image-download-float nodrag nopan"/);
  assert.match(flowSource, /onClick=\{\(event\) => event\.stopPropagation\(\)\}/);
  assert.match(flowSource, /onDoubleClick=\{handleDoubleClick\}/);
  assert.match(flowSource, /fileInputRef\.current\?\.click\(\)/);
  assert.match(flowSource, /双击节点上传图片/);
  assert.match(flowSource, /onPaste/);
  assert.match(flowSource, /const runPromptEditor = useCallback/);
  assert.match(flowSource, /prompteditor.*providerOptions/s);
  assert.match(flowSource, /source\.type === "prompteditor".*isOutputNodeType\(target\.type\)/s);
  assert.match(flowSource, /migratePromptEditorChains/);
  assert.match(flowSource, /type TaskStatus = "queued" \| "running" \| "completed" \| "failed" \| "cancelled"/);
  assert.match(flowSource, /检查输入/);
  assert.match(flowSource, /处理参考素材/);
  assert.match(flowSource, /Codex 处理中/);
  assert.match(flowSource, /写入输出/);
  assert.match(flowSource, /const \[taskConcurrency, setTaskConcurrency\] = useState\(2\)/);
  assert.match(flowSource, /new EventSource\(`\$\{BRIDGE_URL\}\/tasks\/events`\)/);
  assert.match(flowSource, /const TASK_POLL_FALLBACK_MS\s*=\s*3_?000/);
  assert.match(flowSource, /const TASK_POLL_CONNECTED_MS\s*=\s*15_?000/);
  assert.match(flowSource, /\bmergeCanvasTask\b/);
  assert.match(flowSource, /\bmergeTaskLists\b/);
  assert.match(flowSource, /if \(currentIsTerminal\) return current/);
  assert.match(flowSource, /if \(current\.status === "running" && incoming\.status === "queued"\) return current/);
  assert.match(flowSource, /taskStageIndex\(incoming\.stage\) < taskStageIndex\(current\.stage\)/);
  assert.match(flowSource, /events\.onopen\s*=/);
  assert.match(flowSource, /events\.onerror\s*=/);
  assert.match(flowSource, /taskApi<\{ task: CanvasTask \}>\("\/tasks", \{\s*method: "POST"/s);
  assert.doesNotMatch(flowSource, /taskApi<[^>]+>\("\/refine"|fetch\(`\$\{BRIDGE_URL\}\/refine/);
  assert.match(flowSource, /projectId\?: string/);
  assert.match(flowSource, /const belongsToCurrentProject = task\.projectId === projectId;\s*if \(!belongsToCurrentProject\) return;/);
  assert.match(flowSource, /kind: "generation",\s*projectId,/s);
  assert.match(flowSource, /kind: "revision",\s*projectId,/s);
  assert.match(flowSource, /task\.projectId === projectId && ACTIVE_TASK_STATUSES\.has\(task\.status\)/);
  assert.match(flowSource, /provider: String\(payload\.provider \|\| "codex"\)/);
  assert.match(flowSource, /sameProvider && sameModel/);
  assert.match(flowSource, /providerSource\(taskProvider\)/);
  assert.match(flowSource, /delete data\.sessionId/);
  assert.match(flowSource, /这个输出节点已有任务正在排队或运行/);
  assert.match(flowSource, /taskApi<\{ task: CanvasTask \}>\(`\/tasks\/\$\{taskId\}`, \{ method: "DELETE" \}\)/);
  assert.match(flowSource, /<option value=\{1\}>1<\/option><option value=\{2\}>2<\/option><option value=\{3\}>3<\/option>/);
  assert.match(flowSource, /保留最近 20 条任务/);
  assert.match(flowSource, /定位节点/);
  assert.match(flowSource, /查看结果/);
  assert.match(flowSource, /复制错误/);
  assert.match(flowSource, /再次运行/);
  assert.match(flowSource, /清除已结束/);
  assert.match(flowSource, /<aside className=\{`task-center/);
  assert.match(flowSource, /addCanvasNode/);
  assert.match(flowSource, /useGSAP/);
  assert.match(flowSource, /screenToFlowPosition/);
  assert.match(flowSource, /ConnectionLineType\.Bezier/);
  assert.match(flowSource, /curvedEdges/);
  assert.match(flowSource, /function DisconnectableEdge/);
  assert.match(flowSource, /EdgeLabelRenderer/);
  assert.match(flowSource, /aria-label="断开连接"/);
  assert.match(flowSource, /deleteElements\(\{ edges: \[\{ id \}\] \}\)/);
  assert.match(flowSource, /type: "disconnectable"/);
  assert.match(flowSource, /onEdgeContextMenu=\{onEdgeContextMenu\}/);
  assert.match(flowSource, /deleteKeyCode=\{null\}/);
  assert.match(flowSource, /contenteditable.*false/);
  assert.doesNotMatch(flowSource, /smoothstep/);
  assert.match(flowSource, /workspace-shell/);
  assert.match(flowSource, /LIBRARY_STATE_KEY/);
  assert.doesNotMatch(flowSource, /onPointerMove|movePaletteCard/);
  assert.doesNotMatch(flowSource, /type: "direction"|生成规格/);
  assert.match(flowSource, /backgroundProjectEventDecision/);
  assert.match(flowSource, /shouldApplyTaskOutcome/);
  assert.match(flowSource, /beforeunload/);
  assert.match(flowSource, /后台更新可载入/);
  const projectEventStart = flowSource.indexOf('new EventSource(`${BRIDGE_URL}/projects/events`)');
  const projectEventEnd = flowSource.indexOf("const enqueueTask", projectEventStart);
  assert.ok(projectEventStart > 0 && projectEventEnd > projectEventStart, "project event listener source should be discoverable");
  const projectEventSource = flowSource.slice(projectEventStart, projectEventEnd);
  assert.doesNotMatch(projectEventSource, /setNodes\(|setEdges\(|fitView\(|projectApi<CanvasProject>/);

  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(styles, /html\[data-theme="dark"\] \{/);
  assert.match(styles, /--canvas-dot:/);
  assert.match(styles, /\.theme-selector \{/);
  assert.match(styles, /\.api-key-settings-dialog \{/);
  assert.match(styles, /\.api-key-field\.is-configured/);
  assert.match(styles, /html\[data-theme="dark"\] \.core-node/);
  assert.match(styles, /html\[data-theme="dark"\] \.canvas-group-frame/);
  assert.match(styles, /grid-template-columns: var\(--sidebar-width\)/);
  assert.match(styles, /grid-template-columns: var\(--sidebar-width\) minmax\(0, 1fr\) var\(--task-panel-width\)/);
  assert.match(styles, /\.task-center \{/);
  assert.match(styles, /\.task-progress i\.active::after/);
  assert.match(styles, /\.app-chrome \{ height: 104px;/);
  assert.match(styles, /\.canvas-tabs \{ height: 40px;/);
  assert.match(styles, /\.canvas-tab-list \{[^}]*overflow-x: auto;[^}]*overflow-y: hidden;/s);
  assert.match(styles, /\.canvas-tab \{[^}]*height: 36px;/s);
  assert.match(styles, /\.workspace-shell \{[^}]*height: calc\(100dvh - 104px\);/s);
  assert.match(styles, /\.react-flow__node-reference \{ width: 360px; \}/);
  assert.match(styles, /\.react-flow__node-video \{ width: 440px; \}/);
  assert.match(styles, /\.react-flow__node-text \{ width: 380px; \}/);
  assert.match(styles, /\.react-flow__node-imagegenerator \{ width: 520px !important; min-width: 520px !important; \}/);
  assert.match(styles, /\.react-flow__node-videogenerator \{ width: 520px !important; min-width: 520px !important; \}/);
  assert.match(styles, /\.react-flow__node-imageoutput \{ width: 440px; \}/);
  assert.match(styles, /\.react-flow__node-videooutput \{ width: 520px; \}/);
  assert.match(styles, /\.media-output-empty/);
  assert.match(styles, /\.media-settings-dialog/);
  assert.match(styles, /\.media-saved-path/);
  assert.match(styles, /\.image-generation-prompt\.is-linked textarea/);
  assert.match(styles, /\.image-generation-prompt \.prompt-handle/);
  assert.match(styles, /\.react-flow__node-reference \.core-node \{[^}]*width: 100%;[^}]*min-height: 320px;/s);
  assert.match(styles, /\.react-flow__node-reference \.core-node-body \{[^}]*display: flex;[^}]*flex-direction: column;/s);
  assert.match(styles, /\.react-flow__node-reference \.image-only-drop \{[^}]*width: 100%;[^}]*height: 100%;[^}]*min-height: 0;/s);
  assert.match(styles, /\.reference-resize-handle/);
  assert.match(styles, /\.media-output-grid\.is-single/);
  assert.match(styles, /\.preset-library/);
  assert.match(styles, /\.preset-card:hover/);
  assert.match(styles, /\.canvas-group-frame/);
  assert.match(styles, /\.canvas-group-frame\.is-selected/);
  assert.match(styles, /\.group-resize-handle/);
  assert.match(styles, /\.group-title-input/);
  assert.match(styles, /\.group-rename-button/);
  assert.match(styles, /\.image-preview-card:hover \.image-download-float/);
  assert.match(styles, /\.core-node\.is-image-drop-active::after/);
  assert.match(styles, /object-fit: contain/);
  assert.match(styles, /\.node-app\.is-alt-copy/);
  assert.match(styles, /\.canvas-shortcuts-hint/);
  assert.match(styles, /\.edge-disconnect-button/);
  assert.match(styles, /font-family: var\(--font-geist-sans\)/);
  assert.doesNotMatch(styles, /Cabinet Grotesk|node-library-shell/);

  const layoutSource = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  assert.match(layoutSource, /agent-canvas-theme/);
  assert.match(layoutSource, /prefers-color-scheme: dark/);
  assert.match(layoutSource, /root\.dataset\.theme = dark \? "dark" : "light"/);
  assert.match(layoutSource, /suppressHydrationWarning/);
  assert.match(layoutSource, /ResizeObserver loop completed with undelivered notifications\./);
  assert.match(layoutSource, /event\.preventDefault\(\)/);
  assert.match(layoutSource, /event\.stopImmediatePropagation\(\)/);

  const bridgeSource = await readFile(new URL("../scripts/codex-bridge.mjs", import.meta.url), "utf8");
  assert.match(bridgeSource, /pathname === "\/api-key-settings"/);
  assert.match(bridgeSource, /saveApiKeyChanges\(localEnvPath, payload\.changes\)/);
  assert.match(bridgeSource, /\/projects/);
  assert.match(bridgeSource, /pathname === "\/media-settings"/);
  assert.match(bridgeSource, /attachSavedMedia/);
  assert.match(bridgeSource, /backfillCompletedMediaOutputs/);
  assert.match(bridgeSource, /model\/list/);
  assert.match(bridgeSource, /modelReasoningEffort: reasoningEffort/);
  assert.match(bridgeSource, /Agent Canvas 的修改模式/);
  assert.match(bridgeSource, /payload\.taskMode === "revision"/);
  assert.match(bridgeSource, /payload\.videos/);
  assert.match(bridgeSource, /extractVideoFrames/);
  assert.match(bridgeSource, /ffmpeg/);
  assert.match(bridgeSource, /@视频N/);
  assert.match(bridgeSource, /\.prompt-flow-data/);
  assert.match(bridgeSource, /handleAutomationRequest/);
  assert.match(bridgeSource, /persistAutomationTaskOutcome/);
  assert.match(bridgeSource, /handleProjectEvents/);
  assert.match(bridgeSource, /const taskStorePath = join\(dataDirectory, "tasks\.json"\)/);
  assert.match(bridgeSource, /let taskConcurrency = 2/);
  assert.match(bridgeSource, /const CODEX_RUN_TIMEOUT_MS = 10 \* 60_000/);
  assert.match(bridgeSource, /const CODEX_TIMEOUT_MESSAGE = "Codex 处理超过 10 分钟，已停止；可降低思考强度后重试"/);
  assert.match(bridgeSource, /class CodexTimeoutError extends Error/);
  assert.match(bridgeSource, /CODEX_RUN_TIMEOUT_MS/);
  assert.match(bridgeSource, /sortedTaskSummaries\(\)\.slice\(0, 20\)/);
  assert.match(bridgeSource, /runningTaskIds\.size < taskConcurrency/);
  assert.match(bridgeSource, /"Content-Type": "text\/event-stream; charset=utf-8"/);
  assert.match(bridgeSource, /request\.method === "POST" && pathname === "\/tasks"/);
  assert.match(bridgeSource, /request\.method === "PATCH" && pathname === "\/tasks\/config"/);
  assert.match(bridgeSource, /!\[1, 2, 3\]\.includes\(value\)/);
  assert.match(bridgeSource, /request\.method === "DELETE" && match/);
  assert.match(bridgeSource, /controller\?\.abort\("用户取消任务"\)/);
  assert.match(bridgeSource, /task\.outputNodeIds\.some\(\(id\) => outputIds\.has\(id\)\)/);
  assert.match(bridgeSource, /projectId: task\.projectId \?\? null/);
  assert.match(bridgeSource, /const projectId = typeof rawProjectId === "string" \? rawProjectId\.trim\(\) : ""/);
  assert.match(bridgeSource, /projectId: projectId \|\| null/);
  assert.match(bridgeSource, /\(task\.projectId \?\? null\) === meta\.projectId/);
  assert.match(bridgeSource, /projectId: typeof item\.projectId === "string" && validProjectId\(item\.projectId\) \? item\.projectId : null/);

  const projectStoreSource = await readFile(new URL("../scripts/canvas-project-store.mjs", import.meta.url), "utf8");
  assert.match(projectStoreSource, /mediaCount/);
  assert.match(projectStoreSource, /CanvasRevisionConflictError/);
  assert.match(projectStoreSource, /transactionId/);

  const canvasDomainSource = await readFile(new URL("../scripts/canvas-domain.mjs", import.meta.url), "utf8");
  assert.match(canvasDomainSource, /compactCanvasProject/);
  assert.match(canvasDomainSource, /buildNodeTaskRequest/);
  assert.match(canvasDomainSource, /applyTaskResultToProject/);
  assert.match(bridgeSource, /throw new HttpError\(409, `输出节点已有任务/);
  assert.match(bridgeSource, /stage\(onStage, "preparing_media", signal\)/);
  assert.match(bridgeSource, /stage\(onStage, "codex", signal\)/);
  assert.match(bridgeSource, /stage\(onStage, "openrouter", signal\)/);
  assert.match(bridgeSource, /stage\(onStage, GROK_BUILD_PROVIDER_ID, signal\)/);
  assert.match(bridgeSource, /stage\(onStage, ANTIGRAVITY_PROVIDER_ID, signal\)/);
  assert.match(bridgeSource, /stage\(onStage, "writing", signal\)/);
  assert.match(bridgeSource, /task\.kind === "image-generation"/);
  assert.match(bridgeSource, /task\.kind === "video-generation"/);
  assert.match(bridgeSource, /runOpenRouterRefine/);
  assert.match(bridgeSource, /runGrokBuildRefine/);
  assert.match(bridgeSource, /runAntigravityRefine/);
  assert.match(bridgeSource, /normalizeProvider\(payload\?\.provider\)/);
  assert.match(bridgeSource, /provider: task\.provider \|\| "codex"/);
  assert.match(bridgeSource, /item\.provider === ANTIGRAVITY_PROVIDER_ID/);
  assert.match(bridgeSource, /item\.provider === COMFLY_LLM_PROVIDER_ID/);
  assert.match(bridgeSource, /runComflyLlmRefine/);
  assert.match(bridgeSource, /stage\(onStage, COMFLY_LLM_PROVIDER_ID, signal\)/);
  assert.match(bridgeSource, /requestUrl\.searchParams\.get\("provider"\)/);
  assert.match(bridgeSource, /providers: \{[\s\S]*?codex:[\s\S]*?openrouter:/);
  assert.match(bridgeSource, /\[GROK_BUILD_PROVIDER_ID\]: \{/);
  assert.match(bridgeSource, /\[ANTIGRAVITY_PROVIDER_ID\]: \{/);
  assert.match(bridgeSource, /validateStructuredResult\(result\.finalResponse\)/);
});
